In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
import sklearn.metrics
from sklearn.metrics import confusion_matrix, accuracy_score, r2_score
from sklearn.model_selection import train_test_split

In [2]:
def statsmodels_train_test_split(df, stratify=None, **kwargs):

    if stratify is None:
        y, X = df.iloc[:,0], df.drop(columns=df.columns[0])
        X_train, X_test, y_train, y_test = train_test_split(X,y, **kwargs)
    else:
        y, X = stratify, df.drop(columns = stratify.name)
        X_train, X_test, y_train, y_test = train_test_split(X,y,stratify=y, **kwargs)
    
    return pd.concat([X_train, y_train], axis=1), pd.concat([X_test, y_test], axis=1)

Import and read CSV files

In [3]:
df = pd.read_csv('C:\\Users\\Rose\\Desktop\\Capstone4\\smalldf.csv')
dftest = pd.read_csv('C:\\Users\\Rose\\Desktop\\Capstone4\\smalldf.csv')

In [4]:
dftest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442771 entries, 0 to 442770
Data columns (total 29 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Unnamed: 0              442771 non-null  int64
 1   display_id              442771 non-null  int64
 2   uuid                    442771 non-null  object
 3   document_id_x           442771 non-null  int64
 4   timestamp               442771 non-null  int64
 5   platform                442771 non-null  int64
 6   geo_location            442764 non-null  object
 7   source_id               442765 non-null  float64
 8   publisher_id            442765 non-null  float64
 9   publish_time            377774 non-null  object
 10  ad_id                   442771 non-null  int64
 11  clicked                 442771 non-null  int64
 12  document_id_y           442771 non-null  int64
 13  campaign_id             442771 non-null  int64
 14  advertiser_id           442771 non-null  int64
 15  converted_timestamp     442771 non-null  object
 16  timestamp_year          442771 non-null  int64
 17  timestamp_month         442771 non-null  int64
 18  timestamp_day           442771 non-null  int64
 19  timestamp_hour          442771 non-null  int64
 20  timestamp_minute        442771 non-null  int64
 21  timestamp_dayofweek     442771 non-null  int64
 22  the_publish_time        377672 non-null  object
 23  publish_time_year       377672 non-null  float64
 24  publish_time_month      377672 non-null  float64
 25  publish_time_day        377672 non-null  float64
 26  publish_time_hour       377672 non-null  float64
 27  publish_time_minute     377672 non-null  float64
 28  publish_time_dayofweek  377672 non-null  float64
dtypes: float64(8), int64(16), object(5)
memory usage: 98.0+ MB

In [5]:
train, test = statsmodels_train_test_split(dftest)

In [6]:
train.head()

,display_id,uuid,document_id_x,timestamp,platform,geo_location,source_id,publisher_id,publish_time,ad_id,...,timestamp_minute,timestamp_dayofweek,the_publish_time,publish_time_year,publish_time_month,publish_time_day,publish_time_hour,publish_time_minute,publish_time_dayofweek,Unnamed: 0
79444,5298356,61a8249b8b679a,879466,343030874,2,FR>A8,1032.0,1025.0,2015-03-23 06:00:00,184373,...,17,5,2015-03-23 06:00:00.000,2015.0,3.0,23.0,6.0,0.0,0.0,79444
105093,8015122,9446da29d5107f,1179111,554988333,2,PL>86,7369.0,867.0,NaN,75862,...,9,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105093
429883,7762059,7bd12a1cccc36d,1256566,538406774,3,US>OH>515,7736.0,450.0,2016-07-13 00:00:00,304040,...,33,0,2016-07-13 00:00:00.000,2016.0,7.0,13.0,0.0,0.0,2.0,429883
146418,12326500,17ddaefd987760,2222341,821094465,1,US>MO>609,8610.0,1142.0,2016-06-18 09:00:00,8744,...,4,3,2016-06-18 09:00:00.000,2016.0,6.0,18.0,9.0,0.0,5.0,146418
274420,7375237,fd1dac0bcb7757,2250389,506078848,3,US>WV>598,105.0,206.0,2016-06-19 16:00:00,60034,...,34,0,2016-06-19 16:00:00.000,2016.0,6.0,19.0,16.0,0.0,6.0,274420

In [7]:
test.head()

,display_id,uuid,document_id_x,timestamp,platform,geo_location,source_id,publisher_id,publish_time,ad_id,...,timestamp_minute,timestamp_dayofweek,the_publish_time,publish_time_year,publish_time_month,publish_time_day,publish_time_hour,publish_time_minute,publish_time_dayofweek,Unnamed: 0
195185,15891990,b4b0abf8c536a5,1379970,1064264527,2,US>CA>807,10030.0,1089.0,2016-04-14 00:00:00,95112,...,37,6,2016-04-14 00:00:00.000,2016.0,4.0,14.0,0.0,0.0,3.0,195185
306408,10568440,6e43b805ae965a,2344581,712759599,3,US>WI>658,11733.0,828.0,2016-06-20 18:00:00,276173,...,59,2,2016-06-20 18:00:00.000,2016.0,6.0,20.0,18.0,0.0,0.0,306408
35029,149439,48da27ed54353e,1760989,15088201,2,US>MI>505,18.0,1050.0,2016-06-13 11:00:00,93303,...,11,1,2016-06-13 11:00:00.000,2016.0,6.0,13.0,11.0,0.0,0.0,35029
220772,16048320,b73a0701478be7,895645,1073317737,1,US>NY>501,7132.0,850.0,NaN,153383,...,8,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,220772
57409,13927407,3f4ed5e1cb2b32,1827718,917698505,1,US>NH>506,9874.0,1228.0,2016-06-14 18:00:00,89630,...,54,4,2016-06-14 18:00:00.000,2016.0,6.0,14.0,18.0,0.0,1.0,57409

In [8]:
dftest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442771 entries, 0 to 442770
Data columns (total 29 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Unnamed: 0              442771 non-null  int64
 1   display_id              442771 non-null  int64
 2   uuid                    442771 non-null  object
 3   document_id_x           442771 non-null  int64
 4   timestamp               442771 non-null  int64
 5   platform                442771 non-null  int64
 6   geo_location            442764 non-null  object
 7   source_id               442765 non-null  float64
 8   publisher_id            442765 non-null  float64
 9   publish_time            377774 non-null  object
 10  ad_id                   442771 non-null  int64
 11  clicked                 442771 non-null  int64
 12  document_id_y           442771 non-null  int64
 13  campaign_id             442771 non-null  int64
 14  advertiser_id           442771 non-null  int64
 15  converted_timestamp     442771 non-null  object
 16  timestamp_year          442771 non-null  int64
 17  timestamp_month         442771 non-null  int64
 18  timestamp_day           442771 non-null  int64
 19  timestamp_hour          442771 non-null  int64
 20  timestamp_minute        442771 non-null  int64
 21  timestamp_dayofweek     442771 non-null  int64
 22  the_publish_time        377672 non-null  object
 23  publish_time_year       377672 non-null  float64
 24  publish_time_month      377672 non-null  float64
 25  publish_time_day        377672 non-null  float64
 26  publish_time_hour       377672 non-null  float64
 27  publish_time_minute     377672 non-null  float64
 28  publish_time_dayofweek  377672 non-null  float64
dtypes: float64(8), int64(16), object(5)
memory usage: 98.0+ MB

In [9]:
formula = 'clicked ~ C(platform) + C(ad_id)'
model = smf.logit(formula = formula, data=train).fit()
model.summary()

KeyboardInterrupt:

In [24]:
y_pred_test = model.predict(test)
y_pred_test

172391    0.218583
88521     0.231942
46558     0.219512
331526    0.168864
24632     0.173199
            ...
386621    0.174165
385960    0.174512
18206     0.221341
44523     0.176100
351487    0.215979
Length: 110693, dtype: float64

In [25]:
predictions = np.round(y_pred_test)

In [26]:
predictions

172391    0.0
88521     0.0
46558     0.0
331526    0.0
24632     0.0
         ...
386621    0.0
385960    0.0
18206     0.0
44523     0.0
351487    0.0
Length: 110693, dtype: float64

In [27]:
confusion_matrix(test['clicked'], predictions)

array([[89263,     0],
       [21430,     0]], dtype=int64)

In [ ]:
# this is equivalent to 
#formula = 'species ~ C(island) + bill_length_mm + bill_depth_mm + flipper_length_mm + body_mass_g  + C(sex)'

y, X = penguins.species, penguins.drop(columns='species')
X = pd.get_dummies(X, drop_first=True)